### ISSUE TITLE
Flipped UV maps

### ISSUE THREAD

**Issue by Poyoanon** [jpmac26/AceAttorney-MaxScript#1]
Was using the script to test out Holmes, and while I was applying the textures, the UVs are incorrect and are actually flipped (180 on the U scale). While this is minor if you know how to edit UVs, it is pretty tedious.

**Comment by CaptainSwag101** [comment]
Thanks for the bug report, I had actually assumed that this was just the way it needed to be done since that was how the original author wrote the script, but I guess not! Fixed by commit 94a0694b52885fd12c9df762cf7e74e669424813
